export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const COMPOSE_SUCCESS = "COMPOSE_SUCCESS";
export const COMPOSE_FAIL = "COMPOSE_FAIL";

export const UPDATE_INBOX_SUCCESS = "UPDATE_INBOX_SUCCESS";
export const UPDATE_INBOX_FAIL = "UPDATE_INBOX_FAIL";